name: holink
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  url_launcher: ^6.3.0
  table_calendar: ^3.1.2
  http: ^1.2.1
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "ffffff"
  image: assets/logo.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DM_Sans.ttf
        - asset: assets/fonts/DM_Sans.ttf
          weight: 700
        - asset: assets/fonts/DM_Sans_Italic.ttf
          style: italic

dependency_overrides:
  leak_tracker_flutter_testing: any
